apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.38.0
          ports:
            - containerPort: 9090
